### PR TITLE
Fix all the insane duplicate commits and nastiness

### PR DESCRIPTION
**Pull request by nsh87**
This cherry-picks the individual commits to try to remove duplicates so there aren't so many merge conflicts.

You can look at PR #7 for more info on where this PR came from, then trace that back to PR's #3 and #4 for the origin.

### CODE REVIEW

**Comment by nsh87** [comment]
@catterbu: Ok, I think I've gotten the duplicates removed. Please us this PR to check things.

**Comment by nsh87** [comment]
This is now the canonical PR (after PR #7) for dealing with the duplicated commits shit.

**Comment by nsh87** [comment]
@catterbu: I don't want to be up at 2am trying to get everything to build and have 10,000 commits to sort through to figure out where things broke, so I've tried to get rid of the duplicates. I have no idea if the order of them is correct, but at this point, as long as the final files are Ok, let's roll with this.

**Comment by nsh87** [comment]
Looks like there is just one instance of duplicates still, but much better than before.

**Comment by catterbu** [comment]
@nsh87 went thru test file first. finishing up _ehrcorral.py_, then _measures.py_.

**Comment by catterbu** [comment]
@nsh87 just finished _measures.py_. So obvious the `pkgutil` package is the one required to load data in a package. Other than those changes, everything is there. Thanks for that! I will pull this branch down now.

**Comment by catterbu** [comment]
@nsh87 should I delete **add_name_similarity** and **update_measures**? Should the "fix" branches be deleted or left for now?

**Pull request merged**
